name = "Montage"
uuid = "b5316104-0607-4250-a2f2-009686a1a11b"
authors = ["Daniel Bergman <danielrbergman@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
