# Collects every
#     !!! tierjournal "YYYY-MM-DD — Title"
# block under docs/src into docs/src/dev/journal.md, newest first. The blocks
# stay on their own pages too — this is the same source read in time order.
# Also checks that tier blocks run shallowest first.

const JOURNAL_SRC = joinpath(@__DIR__, "src")
const JOURNAL_OUT = joinpath(JOURNAL_SRC, "dev", "journal.md")
# ASCII-only on purpose: the dash separator is trimmed below rather than
# matched here, so the pattern needs no Unicode character class.
const JOURNAL_HEAD = r"^!!!\s+tierjournal\s+\"(\d{4}-\d{2}-\d{2})\s*(.*?)\"\s*$"
journal_title(s) = String(strip(c -> isspace(c) || c == '-' || c == '–' || c == '—', s))

struct JournalEntry
    date::String
    title::String
    body::String
    page::String
end

function journal_entries(path, srcroot)
    entries = JournalEntry[]
    lines = readlines(path)
    i = firstindex(lines)
    while i <= lastindex(lines)
        m = match(JOURNAL_HEAD, rstrip(lines[i]))
        if m === nothing
            i += 1
            continue
        end
        body = String[]
        i += 1
        # The body runs to the first line that is neither blank nor indented.
        while i <= lastindex(lines) &&
              (isempty(strip(lines[i])) || startswith(lines[i], "    "))
            push!(body, chopprefix(lines[i], "    "))
            i += 1
        end
        while !isempty(body) && isempty(strip(body[end]))
            pop!(body)
        end
        push!(entries, JournalEntry(String(m[1]), journal_title(m[2]),
                                    join(body, "\n"), relpath(path, srcroot)))
    end
    return entries
end

# Within a section, tier blocks must appear shallowest first. A reader who
# steps up a tier should find the new material below what they were already
# reading, never spliced in above it.
const TIER_ORDER = ["brief", "full", "dev", "journal"]
const TIER_BLOCK = r"^!!!\s+tier([a-z]+)"

function check_tier_order(path)
    problems = String[]
    infence = false
    section = "(top of file)"
    prev = nothing
    for (n, line) in enumerate(readlines(path))
        s = strip(line)
        if startswith(s, "```")
            infence = !infence
            continue
        end
        infence && continue
        if startswith(s, "#")
            section = strip(lstrip(s, '#'))
            prev = nothing
            continue
        end
        m = match(TIER_BLOCK, s)
        m === nothing && continue
        tier = String(m[1])
        rank = findfirst(==(tier), TIER_ORDER)
        rank === nothing && continue
        if prev === nothing || rank >= prev[1]
            prev = (rank, tier)
        else
            push!(problems, "$path:$n: tier$tier appears after tier$(prev[2]) " *
                            "under \"$section\" — tier blocks go shallowest " *
                            "first (brief, full, dev, journal)")
        end
    end
    return problems
end

function build_journal(; srcroot = JOURNAL_SRC, out = JOURNAL_OUT)
    paths = String[]
    for (root, _, files) in walkdir(srcroot), file in files
        endswith(file, ".md") || continue
        path = joinpath(root, file)
        abspath(path) == abspath(out) && continue
        push!(paths, path)
    end
    sort!(paths)  # deterministic output: the file changes only when entries do

    for path in paths, problem in check_tier_order(path)
        @warn problem     # change @warn to error to fail the build on this
    end

    entries = JournalEntry[]
    for path in paths
        append!(entries, journal_entries(path, srcroot))
    end
    sort!(entries; by = e -> e.date, rev = true, alg = MergeSort)

    mkpath(dirname(out))
    open(out, "w") do io
        println(io, "# Journal\n")
        println(io, "<!-- Generated by docs/journal.jl. Edit the `!!! tierjournal`")
        println(io, "     blocks on the source pages, not this file. -->\n")
        isempty(entries) && println(io, "No entries yet.")
        for e in entries
            println(io, "## ", e.date, " — ", e.title, "\n")
            isempty(e.body) || println(io, e.body, "\n")
            link = relpath(joinpath(srcroot, e.page), dirname(out))
            println(io, "*From [`", e.page, "`](", link, ")*\n")
        end
    end
    @info "journal.jl: $(length(entries)) entries -> $(relpath(out, srcroot))"
    return entries
end

build_journal()
